const CREATIVE = {
    id: 243,
    name: ' test',
    height: 1000,
    width: 1000,
    data: {
        background: 'rgba(255,255,255,0.5)',
        backgroundImage: {
            angle: 0,
            backgroundColor: '',
            fill: '#93dfb8',
            fillRule: 'nonzero',
            flipX: false,
            flipY: false,
            globalCompositeOperation: 'source-over',
            height: 1000,
            left: 0,
            opacity: 1,
            originX: 'left',
            originY: 'top',
            paintFirst: 'fill',
            rx: 0,
            ry: 0,
            scaleX: 1,
            scaleY: 1,
            selectable: false,
            shadow: {
                affectStroke: false,
                blur: 10,
                color: '#9bbdc7',
                nonScaling: false,
                offsetX: 2,
                offsetY: 2,
            },
            skewX: 0,
            skewY: 0,
            stroke: null,
            strokeDashArray: null,
            strokeDashOffset: 0,
            strokeLineCap: 'butt',
            strokeLineJoin: 'miter',
            strokeMiterLimit: 4,
            strokeUniform: false,
            strokeWidth: 0,
            top: 0,
            type: 'rect',
            version: '4.3.1',
            visible: true,
            width: 1000,
        },
        objects: [
            {
                angle: 0,
                backgroundColor: 'transparent',
                charSpacing: 0,
                editable: true,
                fill: '#b33d3d',
                fillRule: 'nonzero',
                flipX: false,
                flipY: false,
                fontFamily: 'arial',
                fontSize: 83.33,
                fontStyle: 'normal',
                fontWeight: 'normal',
                globalCompositeOperation: 'source-atop',
                height: 94.1629,
                id: 'e1ea915bq',
                layerName: 'lorem ',
                left: 1.1464738197,
                lineHeight: 1.16,
                linethrough: false,
                lockUniScaling: true,
                minWidth: 20,
                objectType: 'Text',
                offerType: '',
                opacity: 100,
                originX: 'center',
                originY: 'center',
                overline: false,
                paintFirst: 'fill',
                scaleX: 1,
                scaleY: 1,
                selectable: true,
                shadow: {
                    affectStroke: false,
                    blur: 0,
                    color: 'black',
                    nonScaling: false,
                    offsetX: 0,
                    offsetY: 0,
                },
                skewX: 0,
                skewY: 0,
                splitByGrapheme: false,
                stroke: null,
                strokeDashArray: null,
                strokeDashOffset: 0,
                strokeLineCap: 'butt',
                strokeLineJoin: 'miter',
                strokeMiterLimit: 4,
                strokeUniform: false,
                strokeWidth: 0,
                styles: {},
                text: 'Test',
                textAlign: 'left',
                textBackgroundColor: '',
                top: 171.0391017915,
                type: 'textbox',
                underline: false,
                version: '4.3.1',
                visible: true,
                width: 166.2686358908,
            },
            {
                angle: 0,
                backgroundColor: 'transparent',
                charSpacing: 0,
                editable: true,
                fill: '#ed9393',
                fillRule: 'nonzero',
                flipX: false,
                flipY: false,
                fontFamily: 'arial',
                fontSize: 83.33,
                fontStyle: 'normal',
                fontWeight: 'normal',
                globalCompositeOperation: 'source-atop',
                height: 94.1629,
                id: 'yeyupp18g',
                layerName: 'Global Text B',
                left: 858.0962565415,
                lineHeight: 1.16,
                linethrough: false,
                lockUniScaling: true,
                minWidth: 20,
                objectType: 'Text',
                offerType: '',
                opacity: 100,
                originX: 'center',
                originY: 'center',
                overline: false,
                paintFirst: 'fill',
                scaleX: 1,
                scaleY: 1,
                selectable: true,
                shadow: {
                    affectStroke: false,
                    blur: 0,
                    color: 'black',
                    nonScaling: false,
                    offsetX: 0,
                    offsetY: 0,
                },
                skewX: 0,
                skewY: 0,
                splitByGrapheme: false,
                stroke: null,
                strokeDashArray: null,
                strokeDashOffset: 0,
                strokeLineCap: 'butt',
                strokeLineJoin: 'miter',
                strokeMiterLimit: 4,
                strokeUniform: false,
                strokeWidth: 0,
                styles: {},
                text: 'Global Text B',
                textAlign: 'left',
                textBackgroundColor: '',
                top: 832.9886874804,
                type: 'textbox',
                underline: false,
                version: '4.3.1',
                visible: true,
                width: 565.1141132813,
            },

        ],
        version: '4.3.1',
    }
}
export { CREATIVE }